// Complete list of all countries (195 UN member states + observers)
// hasMap: true = has dedicated @svg-maps package with regions
// All countries can be viewed via the World SVG map extraction

const allCountries = [
  { value: 'Afghanistan', label: '🇦🇫 Afghanistan', hasMap: true },
  { value: 'Albania', label: '🇦🇱 Albania', hasMap: true },
  { value: 'Algeria', label: '🇩🇿 Algeria', hasMap: true },
  { value: 'Andorra', label: '🇦🇩 Andorra', hasMap: true },
  { value: 'Angola', label: '🇦🇴 Angola', hasMap: true },
  { value: 'Antigua and Barbuda', label: '🇦🇬 Antigua and Barbuda', hasMap: true },
  { value: 'Argentina', label: '🇦🇷 Argentina', hasMap: true },
  { value: 'Armenia', label: '🇦🇲 Armenia', hasMap: true },
  { value: 'Australia', label: '🇦🇺 Australia', hasMap: true },
  { value: 'Austria', label: '🇦🇹 Austria', hasMap: true },
  { value: 'Azerbaijan', label: '🇦🇿 Azerbaijan', hasMap: true },
  { value: 'Bahamas', label: '🇧🇸 Bahamas', hasMap: true },
  { value: 'Bahrain', label: '🇧🇭 Bahrain', hasMap: true },
  { value: 'Bangladesh', label: '🇧🇩 Bangladesh', hasMap: true },
  { value: 'Barbados', label: '🇧🇧 Barbados', hasMap: true },
  { value: 'Belarus', label: '🇧🇾 Belarus', hasMap: true },
  { value: 'Belgium', label: '🇧🇪 Belgium', hasMap: true },
  { value: 'Belize', label: '🇧🇿 Belize', hasMap: true },
  { value: 'Benin', label: '🇧🇯 Benin', hasMap: true },
  { value: 'Bhutan', label: '🇧🇹 Bhutan', hasMap: true },
  { value: 'Bolivia', label: '🇧🇴 Bolivia', hasMap: true },
  { value: 'Bosnia and Herzegovina', label: '🇧🇦 Bosnia and Herzegovina', hasMap: true },
  { value: 'Botswana', label: '🇧🇼 Botswana', hasMap: true },
  { value: 'Brazil', label: '🇧🇷 Brazil', hasMap: true },
  { value: 'Brunei', label: '🇧🇳 Brunei', hasMap: true },
  { value: 'Bulgaria', label: '🇧🇬 Bulgaria', hasMap: true },
  { value: 'Burkina Faso', label: '🇧🇫 Burkina Faso', hasMap: true },
  { value: 'Burundi', label: '🇧🇮 Burundi', hasMap: true },
  { value: 'Cambodia', label: '🇰🇭 Cambodia', hasMap: true },
  { value: 'Cameroon', label: '🇨🇲 Cameroon', hasMap: true },
  { value: 'Canada', label: '🇨🇦 Canada', hasMap: true },
  { value: 'Cape Verde', label: '🇨🇻 Cape Verde', hasMap: true },
  { value: 'Central African Republic', label: '🇨🇫 Central African Republic', hasMap: true },
  { value: 'Chad', label: '🇹🇩 Chad', hasMap: true },
  { value: 'Chile', label: '🇨🇱 Chile', hasMap: true },
  { value: 'China', label: '🇨🇳 China', hasMap: true },
  { value: 'Colombia', label: '🇨🇴 Colombia', hasMap: true },
  { value: 'Comoros', label: '🇰🇲 Comoros', hasMap: true },
  { value: 'Congo', label: '🇨🇬 Congo', hasMap: true },
  { value: 'Costa Rica', label: '🇨🇷 Costa Rica', hasMap: true },
  { value: 'Croatia', label: '🇭🇷 Croatia', hasMap: true },
  { value: 'Cuba', label: '🇨🇺 Cuba', hasMap: true },
  { value: 'Cyprus', label: '🇨🇾 Cyprus', hasMap: true },
  { value: 'Czech Republic', label: '🇨🇿 Czech Republic', hasMap: true },
  { value: 'Denmark', label: '🇩🇰 Denmark', hasMap: true },
  { value: 'Djibouti', label: '🇩🇯 Djibouti', hasMap: true },
  { value: 'Dominica', label: '🇩🇲 Dominica', hasMap: true },
  { value: 'Dominican Republic', label: '🇩🇴 Dominican Republic', hasMap: true },
  { value: 'Ecuador', label: '🇪🇨 Ecuador', hasMap: true },
  { value: 'Egypt', label: '🇪🇬 Egypt', hasMap: true },
  { value: 'El Salvador', label: '🇸🇻 El Salvador', hasMap: true },
  { value: 'Equatorial Guinea', label: '🇬🇶 Equatorial Guinea', hasMap: true },
  { value: 'Eritrea', label: '🇪🇷 Eritrea', hasMap: true },
  { value: 'Estonia', label: '🇪🇪 Estonia', hasMap: true },
  { value: 'Eswatini', label: '🇸🇿 Eswatini', hasMap: true },
  { value: 'Ethiopia', label: '🇪🇹 Ethiopia', hasMap: true },
  { value: 'Fiji', label: '🇫🇯 Fiji', hasMap: true },
  { value: 'Finland', label: '🇫🇮 Finland', hasMap: true },
  { value: 'France', label: '🇫🇷 France', hasMap: true },
  { value: 'Gabon', label: '🇬🇦 Gabon', hasMap: true },
  { value: 'Gambia', label: '🇬🇲 Gambia', hasMap: true },
  { value: 'Georgia', label: '🇬🇪 Georgia', hasMap: true },
  { value: 'Germany', label: '🇩🇪 Germany', hasMap: true },
  { value: 'Ghana', label: '🇬🇭 Ghana', hasMap: true },
  { value: 'Greece', label: '🇬🇷 Greece', hasMap: true },
  { value: 'Grenada', label: '🇬🇩 Grenada', hasMap: true },
  { value: 'Guatemala', label: '🇬🇹 Guatemala', hasMap: true },
  { value: 'Guinea', label: '🇬🇳 Guinea', hasMap: true },
  { value: 'Guinea-Bissau', label: '🇬🇼 Guinea-Bissau', hasMap: true },
  { value: 'Guyana', label: '🇬🇾 Guyana', hasMap: true },
  { value: 'Haiti', label: '🇭🇹 Haiti', hasMap: true },
  { value: 'Honduras', label: '🇭🇳 Honduras', hasMap: true },
  { value: 'Hungary', label: '🇭🇺 Hungary', hasMap: true },
  { value: 'Iceland', label: '🇮🇸 Iceland', hasMap: true },
  { value: 'India', label: '🇮🇳 India', hasMap: true },
  { value: 'Indonesia', label: '🇮🇩 Indonesia', hasMap: true },
  { value: 'Iran', label: '🇮🇷 Iran', hasMap: true },
  { value: 'Iraq', label: '🇮🇶 Iraq', hasMap: true },
  { value: 'Ireland', label: '🇮🇪 Ireland', hasMap: true },
  { value: 'Israel', label: '🇮🇱 Israel', hasMap: true },
  { value: 'Italy', label: '🇮🇹 Italy', hasMap: true },
  { value: 'Jamaica', label: '🇯🇲 Jamaica', hasMap: true },
  { value: 'Japan', label: '🇯🇵 Japan', hasMap: true },
  { value: 'Jordan', label: '🇯🇴 Jordan', hasMap: true },
  { value: 'Kazakhstan', label: '🇰🇿 Kazakhstan', hasMap: true },
  { value: 'Kenya', label: '🇰🇪 Kenya', hasMap: true },
  { value: 'Kiribati', label: '🇰🇮 Kiribati', hasMap: true },
  { value: 'Kuwait', label: '🇰🇼 Kuwait', hasMap: true },
  { value: 'Kyrgyzstan', label: '🇰🇬 Kyrgyzstan', hasMap: true },
  { value: 'Laos', label: '🇱🇦 Laos', hasMap: true },
  { value: 'Latvia', label: '🇱🇻 Latvia', hasMap: true },
  { value: 'Lebanon', label: '🇱🇧 Lebanon', hasMap: true },
  { value: 'Lesotho', label: '🇱🇸 Lesotho', hasMap: true },
  { value: 'Liberia', label: '🇱🇷 Liberia', hasMap: true },
  { value: 'Libya', label: '🇱🇾 Libya', hasMap: true },
  { value: 'Liechtenstein', label: '🇱🇮 Liechtenstein', hasMap: true },
  { value: 'Lithuania', label: '🇱🇹 Lithuania', hasMap: true },
  { value: 'Luxembourg', label: '🇱🇺 Luxembourg', hasMap: true },
  { value: 'Madagascar', label: '🇲🇬 Madagascar', hasMap: true },
  { value: 'Malawi', label: '🇲🇼 Malawi', hasMap: true },
  { value: 'Malaysia', label: '🇲🇾 Malaysia', hasMap: true },
  { value: 'Maldives', label: '🇲🇻 Maldives', hasMap: true },
  { value: 'Mali', label: '🇲🇱 Mali', hasMap: true },
  { value: 'Malta', label: '🇲🇹 Malta', hasMap: true },
  { value: 'Marshall Islands', label: '🇲🇭 Marshall Islands', hasMap: true },
  { value: 'Mauritania', label: '🇲🇷 Mauritania', hasMap: true },
  { value: 'Mauritius', label: '🇲🇺 Mauritius', hasMap: true },
  { value: 'Mexico', label: '🇲🇽 Mexico', hasMap: true },
  { value: 'Micronesia', label: '🇫🇲 Micronesia', hasMap: true },
  { value: 'Moldova', label: '🇲🇩 Moldova', hasMap: true },
  { value: 'Monaco', label: '🇲🇨 Monaco', hasMap: true },
  { value: 'Mongolia', label: '🇲🇳 Mongolia', hasMap: true },
  { value: 'Montenegro', label: '🇲🇪 Montenegro', hasMap: true },
  { value: 'Morocco', label: '🇲🇦 Morocco', hasMap: true },
  { value: 'Mozambique', label: '🇲🇿 Mozambique', hasMap: true },
  { value: 'Myanmar', label: '🇲🇲 Myanmar', hasMap: true },
  { value: 'Namibia', label: '🇳🇦 Namibia', hasMap: true },
  { value: 'Nauru', label: '🇳🇷 Nauru', hasMap: true },
  { value: 'Nepal', label: '🇳🇵 Nepal', hasMap: true },
  { value: 'Netherlands', label: '🇳🇱 Netherlands', hasMap: true },
  { value: 'New Zealand', label: '🇳🇿 New Zealand', hasMap: true },
  { value: 'Nicaragua', label: '🇳🇮 Nicaragua', hasMap: true },
  { value: 'Niger', label: '🇳🇪 Niger', hasMap: true },
  { value: 'Nigeria', label: '🇳🇬 Nigeria', hasMap: true },
  { value: 'North Korea', label: '🇰🇵 North Korea', hasMap: true },
  { value: 'North Macedonia', label: '🇲🇰 North Macedonia', hasMap: true },
  { value: 'Norway', label: '🇳🇴 Norway', hasMap: true },
  { value: 'Oman', label: '🇴🇲 Oman', hasMap: true },
  { value: 'Pakistan', label: '🇵🇰 Pakistan', hasMap: true },
  { value: 'Palau', label: '🇵🇼 Palau', hasMap: true },
  { value: 'Palestine', label: '🇵🇸 Palestine', hasMap: true },
  { value: 'Panama', label: '🇵🇦 Panama', hasMap: true },
  { value: 'Papua New Guinea', label: '🇵🇬 Papua New Guinea', hasMap: true },
  { value: 'Paraguay', label: '🇵🇾 Paraguay', hasMap: true },
  { value: 'Peru', label: '🇵🇪 Peru', hasMap: true },
  { value: 'Philippines', label: '🇵🇭 Philippines', hasMap: true },
  { value: 'Poland', label: '🇵🇱 Poland', hasMap: true },
  { value: 'Portugal', label: '🇵🇹 Portugal', hasMap: true },
  { value: 'Qatar', label: '🇶🇦 Qatar', hasMap: true },
  { value: 'Romania', label: '🇷🇴 Romania', hasMap: true },
  { value: 'Russia', label: '🇷🇺 Russia', hasMap: true },
  { value: 'Rwanda', label: '🇷🇼 Rwanda', hasMap: true },
  { value: 'Saint Kitts and Nevis', label: '🇰🇳 Saint Kitts and Nevis', hasMap: true },
  { value: 'Saint Lucia', label: '🇱🇨 Saint Lucia', hasMap: true },
  { value: 'Saint Vincent and the Grenadines', label: '🇻🇨 Saint Vincent', hasMap: true },
  { value: 'Samoa', label: '🇼🇸 Samoa', hasMap: true },
  { value: 'San Marino', label: '🇸🇲 San Marino', hasMap: true },
  { value: 'Sao Tome and Principe', label: '🇸🇹 Sao Tome and Principe', hasMap: true },
  { value: 'Saudi Arabia', label: '🇸🇦 Saudi Arabia', hasMap: true },
  { value: 'Senegal', label: '🇸🇳 Senegal', hasMap: true },
  { value: 'Serbia', label: '🇷🇸 Serbia', hasMap: true },
  { value: 'Seychelles', label: '🇸🇨 Seychelles', hasMap: true },
  { value: 'Sierra Leone', label: '🇸🇱 Sierra Leone', hasMap: true },
  { value: 'Singapore', label: '🇸🇬 Singapore', hasMap: true },
  { value: 'Slovakia', label: '🇸🇰 Slovakia', hasMap: true },
  { value: 'Slovenia', label: '🇸🇮 Slovenia', hasMap: true },
  { value: 'Solomon Islands', label: '🇸🇧 Solomon Islands', hasMap: true },
  { value: 'Somalia', label: '🇸🇴 Somalia', hasMap: true },
  { value: 'South Africa', label: '🇿🇦 South Africa', hasMap: true },
  { value: 'South Korea', label: '🇰🇷 South Korea', hasMap: true },
  { value: 'South Sudan', label: '🇸🇸 South Sudan', hasMap: true },
  { value: 'Spain', label: '🇪🇸 Spain', hasMap: true },
  { value: 'Sri Lanka', label: '🇱🇰 Sri Lanka', hasMap: true },
  { value: 'Sudan', label: '🇸🇩 Sudan', hasMap: true },
  { value: 'Suriname', label: '🇸🇷 Suriname', hasMap: true },
  { value: 'Sweden', label: '🇸🇪 Sweden', hasMap: true },
  { value: 'Switzerland', label: '🇨🇭 Switzerland', hasMap: true },
  { value: 'Syria', label: '🇸🇾 Syria', hasMap: true },
  { value: 'Taiwan', label: '🇹🇼 Taiwan', hasMap: true },
  { value: 'Tajikistan', label: '🇹🇯 Tajikistan', hasMap: true },
  { value: 'Tanzania', label: '🇹🇿 Tanzania', hasMap: true },
  { value: 'Thailand', label: '🇹🇭 Thailand', hasMap: true },
  { value: 'Timor-Leste', label: '🇹🇱 Timor-Leste', hasMap: true },
  { value: 'Togo', label: '🇹🇬 Togo', hasMap: true },
  { value: 'Tonga', label: '🇹🇴 Tonga', hasMap: true },
  { value: 'Trinidad and Tobago', label: '🇹🇹 Trinidad and Tobago', hasMap: true },
  { value: 'Tunisia', label: '🇹🇳 Tunisia', hasMap: true },
  { value: 'Turkey', label: '🇹🇷 Turkey', hasMap: true },
  { value: 'Turkmenistan', label: '🇹🇲 Turkmenistan', hasMap: true },
  { value: 'Tuvalu', label: '🇹🇻 Tuvalu', hasMap: true },
  { value: 'Uganda', label: '🇺🇬 Uganda', hasMap: true },
  { value: 'Ukraine', label: '🇺🇦 Ukraine', hasMap: true },
  { value: 'United Arab Emirates', label: '🇦🇪 UAE', hasMap: true },
  { value: 'United Kingdom', label: '🇬🇧 United Kingdom', hasMap: true },
  { value: 'USA', label: '🇺🇸 United States', hasMap: true },
  { value: 'Uruguay', label: '🇺🇾 Uruguay', hasMap: true },
  { value: 'Uzbekistan', label: '🇺🇿 Uzbekistan', hasMap: true },
  { value: 'Vanuatu', label: '🇻🇺 Vanuatu', hasMap: true },
  { value: 'Vatican City', label: '🇻🇦 Vatican City', hasMap: true },
  { value: 'Venezuela', label: '🇻🇪 Venezuela', hasMap: true },
  { value: 'Vietnam', label: '🇻🇳 Vietnam', hasMap: true },
  { value: 'Yemen', label: '🇾🇪 Yemen', hasMap: true },
  { value: 'Zambia', label: '🇿🇲 Zambia', hasMap: true },
  { value: 'Zimbabwe', label: '🇿🇼 Zimbabwe', hasMap: true },
];

export default allCountries;
export const countriesWithMaps = allCountries.filter(c => c.hasMap);
