const countryCodes = [
  { code: '+1', country: 'USA', flag: '🇺🇸', label: '🇺🇸 +1' },
  { code: '+1', country: 'Canada', flag: '🇨🇦', label: '🇨🇦 +1' },
  { code: '+7', country: 'Russia', flag: '🇷🇺', label: '🇷🇺 +7' },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', label: '🇪🇬 +20' },
  { code: '+27', country: 'South Africa', flag: '🇿🇦', label: '🇿🇦 +27' },
  { code: '+30', country: 'Greece', flag: '🇬🇷', label: '🇬🇷 +30' },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', label: '🇳🇱 +31' },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', label: '🇧🇪 +32' },
  { code: '+33', country: 'France', flag: '🇫🇷', label: '🇫🇷 +33' },
  { code: '+34', country: 'Spain', flag: '🇪🇸', label: '🇪🇸 +34' },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', label: '🇭🇺 +36' },
  { code: '+39', country: 'Italy', flag: '🇮🇹', label: '🇮🇹 +39' },
  { code: '+40', country: 'Romania', flag: '🇷🇴', label: '🇷🇴 +40' },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', label: '🇨🇭 +41' },
  { code: '+43', country: 'Austria', flag: '🇦🇹', label: '🇦🇹 +43' },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', label: '🇬🇧 +44' },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', label: '🇩🇰 +45' },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', label: '🇸🇪 +46' },
  { code: '+47', country: 'Norway', flag: '🇳🇴', label: '🇳🇴 +47' },
  { code: '+48', country: 'Poland', flag: '🇵🇱', label: '🇵🇱 +48' },
  { code: '+49', country: 'Germany', flag: '🇩🇪', label: '🇩🇪 +49' },
  { code: '+51', country: 'Peru', flag: '🇵🇪', label: '🇵🇪 +51' },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', label: '🇲🇽 +52' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', label: '🇨🇺 +53' },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', label: '🇦🇷 +54' },
  { code: '+55', country: 'Brazil', flag: '🇧🇷', label: '🇧🇷 +55' },
  { code: '+56', country: 'Chile', flag: '🇨🇱', label: '🇨🇱 +56' },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', label: '🇨🇴 +57' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', label: '🇻🇪 +58' },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', label: '🇲🇾 +60' },
  { code: '+61', country: 'Australia', flag: '🇦🇺', label: '🇦🇺 +61' },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', label: '🇮🇩 +62' },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', label: '🇵🇭 +63' },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', label: '🇳🇿 +64' },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', label: '🇸🇬 +65' },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', label: '🇹🇭 +66' },
  { code: '+81', country: 'Japan', flag: '🇯🇵', label: '🇯🇵 +81' },
  { code: '+82', country: 'South Korea', flag: '🇰🇷', label: '🇰🇷 +82' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', label: '🇻🇳 +84' },
  { code: '+86', country: 'China', flag: '🇨🇳', label: '🇨🇳 +86' },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', label: '🇹🇷 +90' },
  { code: '+91', country: 'India', flag: '🇮🇳', label: '🇮🇳 +91' },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', label: '🇵🇰 +92' },
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', label: '🇦🇫 +93' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', label: '🇱🇰 +94' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', label: '🇲🇲 +95' },
  { code: '+98', country: 'Iran', flag: '🇮🇷', label: '🇮🇷 +98' },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', label: '🇲🇦 +212' },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', label: '🇩🇿 +213' },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', label: '🇹🇳 +216' },
  { code: '+218', country: 'Libya', flag: '🇱🇾', label: '🇱🇾 +218' },
  { code: '+220', country: 'Gambia', flag: '🇬🇲', label: '🇬🇲 +220' },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', label: '🇸🇳 +221' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', label: '🇬🇭 +233' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', label: '🇳🇬 +234' },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', label: '🇸🇩 +249' },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', label: '🇪🇹 +251' },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', label: '🇰🇪 +254' },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', label: '🇹🇿 +255' },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', label: '🇺🇬 +256' },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', label: '🇿🇲 +260' },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', label: '🇿🇼 +263' },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', label: '🇮🇪 +353' },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', label: '🇮🇸 +354' },
  { code: '+358', country: 'Finland', flag: '🇫🇮', label: '🇫🇮 +358' },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', label: '🇱🇹 +370' },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', label: '🇱🇻 +371' },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', label: '🇪🇪 +372' },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', label: '🇺🇦 +380' },
  { code: '+420', country: 'Czech Republic', flag: '🇨🇿', label: '🇨🇿 +420' },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', label: '🇸🇰 +421' },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', label: '🇧🇩 +880' },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', label: '🇲🇻 +960' },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', label: '🇱🇧 +961' },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', label: '🇯🇴 +962' },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', label: '🇮🇶 +964' },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', label: '🇸🇦 +966' },
  { code: '+968', country: 'Oman', flag: '🇴🇲', label: '🇴🇲 +968' },
  { code: '+971', country: 'UAE', flag: '🇦🇪', label: '🇦🇪 +971' },
  { code: '+972', country: 'Israel', flag: '🇮🇱', label: '🇮🇱 +972' },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', label: '🇶🇦 +974' },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', label: '🇧🇹 +975' },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', label: '🇲🇳 +976' },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', label: '🇳🇵 +977' },
  { code: '+992', country: 'Tajikistan', flag: '🇹🇯', label: '🇹🇯 +992' },
  { code: '+993', country: 'Turkmenistan', flag: '🇹🇲', label: '🇹🇲 +993' },
  { code: '+994', country: 'Azerbaijan', flag: '🇦🇿', label: '🇦🇿 +994' },
  { code: '+995', country: 'Georgia', flag: '🇬🇪', label: '🇬🇪 +995' },
  { code: '+998', country: 'Uzbekistan', flag: '🇺🇿', label: '🇺🇿 +998' },
];

export default countryCodes;
