const countryCodes = [
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', label: '🇦🇫 +93' },
  { code: '+355', country: 'Albania', flag: '🇦🇱', label: '🇦🇱 +355' },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', label: '🇩🇿 +213' },
  { code: '+376', country: 'Andorra', flag: '🇦🇩', label: '🇦🇩 +376' },
  { code: '+244', country: 'Angola', flag: '🇦🇴', label: '🇦🇴 +244' },
  { code: '+1-268', country: 'Antigua and Barbuda', flag: '🇦🇬', label: '🇦🇬 +1-268' },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', label: '🇦🇷 +54' },
  { code: '+374', country: 'Armenia', flag: '🇦🇲', label: '🇦🇲 +374' },
  { code: '+61', country: 'Australia', flag: '🇦🇺', label: '🇦🇺 +61' },
  { code: '+43', country: 'Austria', flag: '🇦🇹', label: '🇦🇹 +43' },
  { code: '+994', country: 'Azerbaijan', flag: '🇦🇿', label: '🇦🇿 +994' },
  { code: '+1-242', country: 'Bahamas', flag: '🇧🇸', label: '🇧🇸 +1-242' },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', label: '🇧🇭 +973' },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', label: '🇧🇩 +880' },
  { code: '+1-246', country: 'Barbados', flag: '🇧🇧', label: '🇧🇧 +1-246' },
  { code: '+375', country: 'Belarus', flag: '🇧🇾', label: '🇧🇾 +375' },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', label: '🇧🇪 +32' },
  { code: '+501', country: 'Belize', flag: '🇧🇿', label: '🇧🇿 +501' },
  { code: '+229', country: 'Benin', flag: '🇧🇯', label: '🇧🇯 +229' },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', label: '🇧🇹 +975' },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴', label: '🇧🇴 +591' },
  { code: '+387', country: 'Bosnia and Herzegovina', flag: '🇧🇦', label: '🇧🇦 +387' },
  { code: '+267', country: 'Botswana', flag: '🇧🇼', label: '🇧🇼 +267' },
  { code: '+55', country: 'Brazil', flag: '🇧🇷', label: '🇧🇷 +55' },
  { code: '+673', country: 'Brunei', flag: '🇧🇳', label: '🇧🇳 +673' },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬', label: '🇧🇬 +359' },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫', label: '🇧🇫 +226' },
  { code: '+257', country: 'Burundi', flag: '🇧🇮', label: '🇧🇮 +257' },
  { code: '+238', country: 'Cabo Verde', flag: '🇨🇻', label: '🇨🇻 +238' },
  { code: '+855', country: 'Cambodia', flag: '🇰🇭', label: '🇰🇭 +855' },
  { code: '+237', country: 'Cameroon', flag: '🇨🇲', label: '🇨🇲 +237' },
  { code: '+1', country: 'Canada', flag: '🇨🇦', label: '🇨🇦 +1' },
  { code: '+236', country: 'Central African Republic', flag: '🇨🇫', label: '🇨🇫 +236' },
  { code: '+235', country: 'Chad', flag: '🇹🇩', label: '🇹🇩 +235' },
  { code: '+56', country: 'Chile', flag: '🇨🇱', label: '🇨🇱 +56' },
  { code: '+86', country: 'China', flag: '🇨🇳', label: '🇨🇳 +86' },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', label: '🇨🇴 +57' },
  { code: '+269', country: 'Comoros', flag: '🇰🇲', label: '🇰🇲 +269' },
  { code: '+242', country: 'Congo (Republic)', flag: '🇨🇬', label: '🇨🇬 +242' },
  { code: '+243', country: 'Congo (DRC)', flag: '🇨🇩', label: '🇨🇩 +243' },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷', label: '🇨🇷 +506' },
  { code: '+225', country: "Cote d'Ivoire", flag: '🇨🇮', label: '🇨🇮 +225' },
  { code: '+385', country: 'Croatia', flag: '🇭🇷', label: '🇭🇷 +385' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', label: '🇨🇺 +53' },
  { code: '+357', country: 'Cyprus', flag: '🇨🇾', label: '🇨🇾 +357' },
  { code: '+420', country: 'Czech Republic', flag: '🇨🇿', label: '🇨🇿 +420' },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', label: '🇩🇰 +45' },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯', label: '🇩🇯 +253' },
  { code: '+1-767', country: 'Dominica', flag: '🇩🇲', label: '🇩🇲 +1-767' },
  { code: '+1-809', country: 'Dominican Republic', flag: '🇩🇴', label: '🇩🇴 +1-809' },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨', label: '🇪🇨 +593' },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', label: '🇪🇬 +20' },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻', label: '🇸🇻 +503' },
  { code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶', label: '🇬🇶 +240' },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷', label: '🇪🇷 +291' },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', label: '🇪🇪 +372' },
  { code: '+268', country: 'Eswatini', flag: '🇸🇿', label: '🇸🇿 +268' },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', label: '🇪🇹 +251' },
  { code: '+679', country: 'Fiji', flag: '🇫🇯', label: '🇫🇯 +679' },
  { code: '+358', country: 'Finland', flag: '🇫🇮', label: '🇫🇮 +358' },
  { code: '+33', country: 'France', flag: '🇫🇷', label: '🇫🇷 +33' },
  { code: '+241', country: 'Gabon', flag: '🇬🇦', label: '🇬🇦 +241' },
  { code: '+220', country: 'Gambia', flag: '🇬🇲', label: '🇬🇲 +220' },
  { code: '+995', country: 'Georgia', flag: '🇬🇪', label: '🇬🇪 +995' },
  { code: '+49', country: 'Germany', flag: '🇩🇪', label: '🇩🇪 +49' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', label: '🇬🇭 +233' },
  { code: '+30', country: 'Greece', flag: '🇬🇷', label: '🇬🇷 +30' },
  { code: '+1-473', country: 'Grenada', flag: '🇬🇩', label: '🇬🇩 +1-473' },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹', label: '🇬🇹 +502' },
  { code: '+224', country: 'Guinea', flag: '🇬🇳', label: '🇬🇳 +224' },
  { code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼', label: '🇬🇼 +245' },
  { code: '+592', country: 'Guyana', flag: '🇬🇾', label: '🇬🇾 +592' },
  { code: '+509', country: 'Haiti', flag: '🇭🇹', label: '🇭🇹 +509' },
  { code: '+504', country: 'Honduras', flag: '🇭🇳', label: '🇭🇳 +504' },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', label: '🇭🇺 +36' },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', label: '🇮🇸 +354' },
  { code: '+91', country: 'India', flag: '🇮🇳', label: '🇮🇳 +91' },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', label: '🇮🇩 +62' },
  { code: '+98', country: 'Iran', flag: '🇮🇷', label: '🇮🇷 +98' },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', label: '🇮🇶 +964' },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', label: '🇮🇪 +353' },
  { code: '+972', country: 'Israel', flag: '🇮🇱', label: '🇮🇱 +972' },
  { code: '+39', country: 'Italy', flag: '🇮🇹', label: '🇮🇹 +39' },
  { code: '+1-876', country: 'Jamaica', flag: '🇯🇲', label: '🇯🇲 +1-876' },
  { code: '+81', country: 'Japan', flag: '🇯🇵', label: '🇯🇵 +81' },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', label: '🇯🇴 +962' },
  { code: '+7', country: 'Kazakhstan', flag: '🇰🇿', label: '🇰🇿 +7' },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', label: '🇰🇪 +254' },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮', label: '🇰🇮 +686' },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', label: '🇰🇼 +965' },
  { code: '+996', country: 'Kyrgyzstan', flag: '🇰🇬', label: '🇰🇬 +996' },
  { code: '+856', country: 'Laos', flag: '🇱🇦', label: '🇱🇦 +856' },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', label: '🇱🇻 +371' },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', label: '🇱🇧 +961' },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸', label: '🇱🇸 +266' },
  { code: '+231', country: 'Liberia', flag: '🇱🇷', label: '🇱🇷 +231' },
  { code: '+218', country: 'Libya', flag: '🇱🇾', label: '🇱🇾 +218' },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮', label: '🇱🇮 +423' },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', label: '🇱🇹 +370' },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺', label: '🇱🇺 +352' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬', label: '🇲🇬 +261' },
  { code: '+265', country: 'Malawi', flag: '🇲🇼', label: '🇲🇼 +265' },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', label: '🇲🇾 +60' },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', label: '🇲🇻 +960' },
  { code: '+223', country: 'Mali', flag: '🇲🇱', label: '🇲🇱 +223' },
  { code: '+356', country: 'Malta', flag: '🇲🇹', label: '🇲🇹 +356' },
  { code: '+692', country: 'Marshall Islands', flag: '🇲🇭', label: '🇲🇭 +692' },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷', label: '🇲🇷 +222' },
  { code: '+230', country: 'Mauritius', flag: '🇲🇺', label: '🇲🇺 +230' },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', label: '🇲🇽 +52' },
  { code: '+691', country: 'Micronesia', flag: '🇫🇲', label: '🇫🇲 +691' },
  { code: '+373', country: 'Moldova', flag: '🇲🇩', label: '🇲🇩 +373' },
  { code: '+377', country: 'Monaco', flag: '🇲🇨', label: '🇲🇨 +377' },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', label: '🇲🇳 +976' },
  { code: '+382', country: 'Montenegro', flag: '🇲🇪', label: '🇲🇪 +382' },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', label: '🇲🇦 +212' },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿', label: '🇲🇿 +258' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', label: '🇲🇲 +95' },
  { code: '+264', country: 'Namibia', flag: '🇳🇦', label: '🇳🇦 +264' },
  { code: '+674', country: 'Nauru', flag: '🇳🇷', label: '🇳🇷 +674' },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', label: '🇳🇵 +977' },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', label: '🇳🇱 +31' },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', label: '🇳🇿 +64' },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮', label: '🇳🇮 +505' },
  { code: '+227', country: 'Niger', flag: '🇳🇪', label: '🇳🇪 +227' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', label: '🇳🇬 +234' },
  { code: '+850', country: 'North Korea', flag: '🇰🇵', label: '🇰🇵 +850' },
  { code: '+389', country: 'North Macedonia', flag: '🇲🇰', label: '🇲🇰 +389' },
  { code: '+47', country: 'Norway', flag: '🇳🇴', label: '🇳🇴 +47' },
  { code: '+968', country: 'Oman', flag: '🇴🇲', label: '🇴🇲 +968' },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', label: '🇵🇰 +92' },
  { code: '+680', country: 'Palau', flag: '🇵🇼', label: '🇵🇼 +680' },
  { code: '+970', country: 'Palestine', flag: '🇵🇸', label: '🇵🇸 +970' },
  { code: '+507', country: 'Panama', flag: '🇵🇦', label: '🇵🇦 +507' },
  { code: '+675', country: 'Papua New Guinea', flag: '🇵🇬', label: '🇵🇬 +675' },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾', label: '🇵🇾 +595' },
  { code: '+51', country: 'Peru', flag: '🇵🇪', label: '🇵🇪 +51' },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', label: '🇵🇭 +63' },
  { code: '+48', country: 'Poland', flag: '🇵🇱', label: '🇵🇱 +48' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹', label: '🇵🇹 +351' },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', label: '🇶🇦 +974' },
  { code: '+40', country: 'Romania', flag: '🇷🇴', label: '🇷🇴 +40' },
  { code: '+7', country: 'Russia', flag: '🇷🇺', label: '🇷🇺 +7' },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼', label: '🇷🇼 +250' },
  { code: '+1-869', country: 'Saint Kitts and Nevis', flag: '🇰🇳', label: '🇰🇳 +1-869' },
  { code: '+1-758', country: 'Saint Lucia', flag: '🇱🇨', label: '🇱🇨 +1-758' },
  { code: '+1-784', country: 'Saint Vincent and the Grenadines', flag: '🇻🇨', label: '🇻🇨 +1-784' },
  { code: '+685', country: 'Samoa', flag: '🇼🇸', label: '🇼🇸 +685' },
  { code: '+378', country: 'San Marino', flag: '🇸🇲', label: '🇸🇲 +378' },
  { code: '+239', country: 'Sao Tome and Principe', flag: '🇸🇹', label: '🇸🇹 +239' },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', label: '🇸🇦 +966' },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', label: '🇸🇳 +221' },
  { code: '+381', country: 'Serbia', flag: '🇷🇸', label: '🇷🇸 +381' },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨', label: '🇸🇨 +248' },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱', label: '🇸🇱 +232' },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', label: '🇸🇬 +65' },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', label: '🇸🇰 +421' },
  { code: '+386', country: 'Slovenia', flag: '🇸🇮', label: '🇸🇮 +386' },
  { code: '+677', country: 'Solomon Islands', flag: '🇸🇧', label: '🇸🇧 +677' },
  { code: '+252', country: 'Somalia', flag: '🇸🇴', label: '🇸🇴 +252' },
  { code: '+27', country: 'South Africa', flag: '🇿🇦', label: '🇿🇦 +27' },
  { code: '+82', country: 'South Korea', flag: '🇰🇷', label: '🇰🇷 +82' },
  { code: '+211', country: 'South Sudan', flag: '🇸🇸', label: '🇸🇸 +211' },
  { code: '+34', country: 'Spain', flag: '🇪🇸', label: '🇪🇸 +34' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', label: '🇱🇰 +94' },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', label: '🇸🇩 +249' },
  { code: '+597', country: 'Suriname', flag: '🇸🇷', label: '🇸🇷 +597' },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', label: '🇸🇪 +46' },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', label: '🇨🇭 +41' },
  { code: '+963', country: 'Syria', flag: '🇸🇾', label: '🇸🇾 +963' },
  { code: '+886', country: 'Taiwan', flag: '🇹🇼', label: '🇹🇼 +886' },
  { code: '+992', country: 'Tajikistan', flag: '🇹🇯', label: '🇹🇯 +992' },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', label: '🇹🇿 +255' },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', label: '🇹🇭 +66' },
  { code: '+670', country: 'Timor-Leste', flag: '🇹🇱', label: '🇹🇱 +670' },
  { code: '+228', country: 'Togo', flag: '🇹🇬', label: '🇹🇬 +228' },
  { code: '+676', country: 'Tonga', flag: '🇹🇴', label: '🇹🇴 +676' },
  { code: '+1-868', country: 'Trinidad and Tobago', flag: '🇹🇹', label: '🇹🇹 +1-868' },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', label: '🇹🇳 +216' },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', label: '🇹🇷 +90' },
  { code: '+993', country: 'Turkmenistan', flag: '🇹🇲', label: '🇹🇲 +993' },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻', label: '🇹🇻 +688' },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', label: '🇺🇬 +256' },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', label: '🇺🇦 +380' },
  { code: '+971', country: 'United Arab Emirates', flag: '🇦🇪', label: '🇦🇪 +971' },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', label: '🇬🇧 +44' },
  { code: '+1', country: 'United States', flag: '🇺🇸', label: '🇺🇸 +1' },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾', label: '🇺🇾 +598' },
  { code: '+998', country: 'Uzbekistan', flag: '🇺🇿', label: '🇺🇿 +998' },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺', label: '🇻🇺 +678' },
  { code: '+379', country: 'Vatican City', flag: '🇻🇦', label: '🇻🇦 +379' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', label: '🇻🇪 +58' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', label: '🇻🇳 +84' },
  { code: '+967', country: 'Yemen', flag: '🇾🇪', label: '🇾🇪 +967' },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', label: '🇿🇲 +260' },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', label: '🇿🇼 +263' },
];

export default countryCodes;
