// All countries with flag emojis
// Countries with hasMap: true have interactive SVG maps
const allCountries = [
  { value: 'Afghanistan', label: '🇦🇫 Afghanistan' },
  { value: 'Albania', label: '🇦🇱 Albania' },
  { value: 'Algeria', label: '🇩🇿 Algeria' },
  { value: 'Andorra', label: '🇦🇩 Andorra' },
  { value: 'Angola', label: '🇦🇴 Angola' },
  { value: 'Antigua and Barbuda', label: '🇦🇬 Antigua and Barbuda' },
  { value: 'Argentina', label: '🇦🇷 Argentina' },
  { value: 'Armenia', label: '🇦🇲 Armenia' },
  { value: 'Australia', label: '🇦🇺 Australia' },
  { value: 'Austria', label: '🇦🇹 Austria' },
  { value: 'Azerbaijan', label: '🇦🇿 Azerbaijan' },
  { value: 'Bahamas', label: '🇧🇸 Bahamas' },
  { value: 'Bahrain', label: '🇧🇭 Bahrain' },
  { value: 'Bangladesh', label: '🇧🇩 Bangladesh' },
  { value: 'Barbados', label: '🇧🇧 Barbados' },
  { value: 'Belarus', label: '🇧🇾 Belarus' },
  { value: 'Belgium', label: '🇧🇪 Belgium' },
  { value: 'Belize', label: '🇧🇿 Belize' },
  { value: 'Benin', label: '🇧🇯 Benin' },
  { value: 'Bhutan', label: '🇧🇹 Bhutan' },
  { value: 'Bolivia', label: '🇧🇴 Bolivia' },
  { value: 'Bosnia and Herzegovina', label: '🇧🇦 Bosnia and Herzegovina' },
  { value: 'Botswana', label: '🇧🇼 Botswana' },
  { value: 'Brazil', label: '🇧🇷 Brazil', hasMap: true },
  { value: 'Brunei', label: '🇧🇳 Brunei' },
  { value: 'Bulgaria', label: '🇧🇬 Bulgaria' },
  { value: 'Burkina Faso', label: '🇧🇫 Burkina Faso' },
  { value: 'Burundi', label: '🇧🇮 Burundi' },
  { value: 'Cambodia', label: '🇰🇭 Cambodia' },
  { value: 'Cameroon', label: '🇨🇲 Cameroon' },
  { value: 'Canada', label: '🇨🇦 Canada', hasMap: true },
  { value: 'Central African Republic', label: '🇨🇫 Central African Republic' },
  { value: 'Chad', label: '🇹🇩 Chad' },
  { value: 'Chile', label: '🇨🇱 Chile' },
  { value: 'China', label: '🇨🇳 China' },
  { value: 'Colombia', label: '🇨🇴 Colombia' },
  { value: 'Congo', label: '🇨🇬 Congo' },
  { value: 'Costa Rica', label: '🇨🇷 Costa Rica' },
  { value: 'Croatia', label: '🇭🇷 Croatia' },
  { value: 'Cuba', label: '🇨🇺 Cuba' },
  { value: 'Cyprus', label: '🇨🇾 Cyprus' },
  { value: 'Czech Republic', label: '🇨🇿 Czech Republic' },
  { value: 'Denmark', label: '🇩🇰 Denmark' },
  { value: 'Dominican Republic', label: '🇩🇴 Dominican Republic' },
  { value: 'Ecuador', label: '🇪🇨 Ecuador' },
  { value: 'Egypt', label: '🇪🇬 Egypt' },
  { value: 'El Salvador', label: '🇸🇻 El Salvador' },
  { value: 'Estonia', label: '🇪🇪 Estonia' },
  { value: 'Ethiopia', label: '🇪🇹 Ethiopia' },
  { value: 'Fiji', label: '🇫🇯 Fiji' },
  { value: 'Finland', label: '🇫🇮 Finland' },
  { value: 'France', label: '🇫🇷 France', hasMap: true },
  { value: 'Gabon', label: '🇬🇦 Gabon' },
  { value: 'Georgia', label: '🇬🇪 Georgia' },
  { value: 'Germany', label: '🇩🇪 Germany', hasMap: true },
  { value: 'Ghana', label: '🇬🇭 Ghana' },
  { value: 'Greece', label: '🇬🇷 Greece' },
  { value: 'Guatemala', label: '🇬🇹 Guatemala' },
  { value: 'Haiti', label: '🇭🇹 Haiti' },
  { value: 'Honduras', label: '🇭🇳 Honduras' },
  { value: 'Hungary', label: '🇭🇺 Hungary' },
  { value: 'Iceland', label: '🇮🇸 Iceland' },
  { value: 'India', label: '🇮🇳 India', hasMap: true },
  { value: 'Indonesia', label: '🇮🇩 Indonesia' },
  { value: 'Iran', label: '🇮🇷 Iran' },
  { value: 'Iraq', label: '🇮🇶 Iraq' },
  { value: 'Ireland', label: '🇮🇪 Ireland' },
  { value: 'Israel', label: '🇮🇱 Israel' },
  { value: 'Italy', label: '🇮🇹 Italy', hasMap: true },
  { value: 'Jamaica', label: '🇯🇲 Jamaica' },
  { value: 'Japan', label: '🇯🇵 Japan', hasMap: true },
  { value: 'Jordan', label: '🇯🇴 Jordan' },
  { value: 'Kazakhstan', label: '🇰🇿 Kazakhstan' },
  { value: 'Kenya', label: '🇰🇪 Kenya' },
  { value: 'Kuwait', label: '🇰🇼 Kuwait' },
  { value: 'Laos', label: '🇱🇦 Laos' },
  { value: 'Latvia', label: '🇱🇻 Latvia' },
  { value: 'Lebanon', label: '🇱🇧 Lebanon' },
  { value: 'Libya', label: '🇱🇾 Libya' },
  { value: 'Lithuania', label: '🇱🇹 Lithuania' },
  { value: 'Luxembourg', label: '🇱🇺 Luxembourg' },
  { value: 'Madagascar', label: '🇲🇬 Madagascar' },
  { value: 'Malaysia', label: '🇲🇾 Malaysia' },
  { value: 'Maldives', label: '🇲🇻 Maldives' },
  { value: 'Mali', label: '🇲🇱 Mali' },
  { value: 'Malta', label: '🇲🇹 Malta' },
  { value: 'Mexico', label: '🇲🇽 Mexico', hasMap: true },
  { value: 'Mongolia', label: '🇲🇳 Mongolia' },
  { value: 'Morocco', label: '🇲🇦 Morocco' },
  { value: 'Mozambique', label: '🇲🇿 Mozambique' },
  { value: 'Myanmar', label: '🇲🇲 Myanmar' },
  { value: 'Namibia', label: '🇳🇦 Namibia' },
  { value: 'Nepal', label: '🇳🇵 Nepal' },
  { value: 'Netherlands', label: '🇳🇱 Netherlands' },
  { value: 'New Zealand', label: '🇳🇿 New Zealand' },
  { value: 'Nicaragua', label: '🇳🇮 Nicaragua' },
  { value: 'Nigeria', label: '🇳🇬 Nigeria' },
  { value: 'North Korea', label: '🇰🇵 North Korea' },
  { value: 'Norway', label: '🇳🇴 Norway' },
  { value: 'Oman', label: '🇴🇲 Oman' },
  { value: 'Pakistan', label: '🇵🇰 Pakistan' },
  { value: 'Panama', label: '🇵🇦 Panama' },
  { value: 'Paraguay', label: '🇵🇾 Paraguay' },
  { value: 'Peru', label: '🇵🇪 Peru' },
  { value: 'Philippines', label: '🇵🇭 Philippines' },
  { value: 'Poland', label: '🇵🇱 Poland' },
  { value: 'Portugal', label: '🇵🇹 Portugal' },
  { value: 'Qatar', label: '🇶🇦 Qatar' },
  { value: 'Romania', label: '🇷🇴 Romania' },
  { value: 'Russia', label: '🇷🇺 Russia' },
  { value: 'Rwanda', label: '🇷🇼 Rwanda' },
  { value: 'Saudi Arabia', label: '🇸🇦 Saudi Arabia' },
  { value: 'Senegal', label: '🇸🇳 Senegal' },
  { value: 'Serbia', label: '🇷🇸 Serbia' },
  { value: 'Singapore', label: '🇸🇬 Singapore' },
  { value: 'Slovakia', label: '🇸🇰 Slovakia' },
  { value: 'Slovenia', label: '🇸🇮 Slovenia' },
  { value: 'Somalia', label: '🇸🇴 Somalia' },
  { value: 'South Africa', label: '🇿🇦 South Africa' },
  { value: 'South Korea', label: '🇰🇷 South Korea' },
  { value: 'Spain', label: '🇪🇸 Spain', hasMap: true },
  { value: 'Sri Lanka', label: '🇱🇰 Sri Lanka' },
  { value: 'Sudan', label: '🇸🇩 Sudan' },
  { value: 'Sweden', label: '🇸🇪 Sweden' },
  { value: 'Switzerland', label: '🇨🇭 Switzerland' },
  { value: 'Syria', label: '🇸🇾 Syria' },
  { value: 'Taiwan', label: '🇹🇼 Taiwan' },
  { value: 'Tanzania', label: '🇹🇿 Tanzania' },
  { value: 'Thailand', label: '🇹🇭 Thailand' },
  { value: 'Tunisia', label: '🇹🇳 Tunisia' },
  { value: 'Turkey', label: '🇹🇷 Turkey' },
  { value: 'Uganda', label: '🇺🇬 Uganda' },
  { value: 'Ukraine', label: '🇺🇦 Ukraine' },
  { value: 'United Arab Emirates', label: '🇦🇪 UAE' },
  { value: 'United Kingdom', label: '🇬🇧 United Kingdom' },
  { value: 'USA', label: '🇺🇸 United States', hasMap: true },
  { value: 'Uruguay', label: '🇺🇾 Uruguay' },
  { value: 'Uzbekistan', label: '🇺🇿 Uzbekistan' },
  { value: 'Venezuela', label: '🇻🇪 Venezuela' },
  { value: 'Vietnam', label: '🇻🇳 Vietnam' },
  { value: 'Yemen', label: '🇾🇪 Yemen' },
  { value: 'Zambia', label: '🇿🇲 Zambia' },
  { value: 'Zimbabwe', label: '🇿🇼 Zimbabwe' },
];

export default allCountries;
export const countriesWithMaps = allCountries.filter(c => c.hasMap);
