// Curated travel taglines for the Download-Map "Inspire me" picker and the
// inline "Generate by AI" button. 500+ lines grouped loosely by mood so the
// UI can shuffle in a way that still feels varied.

const WANDERLUST = [
  "Collecting stamps, not stuff.",
  "Borders are just suggestions.",
  "Home is where my boarding pass takes me.",
  "Some call it wanderlust. I call it Tuesday.",
  "Postcards and pins — that's my love language.",
  "My passport has better taste than I do.",
  "Jet lag is a small price for a big world.",
  "Living in the pages of my own travel journal.",
  "The world is my canvas. Stamps are my paint.",
  "Travel is the only thing you buy that makes you richer.",
  "Wander often, wonder always.",
  "Ever the wanderer, never the stranger.",
  "Born to travel. Forced to work.",
  "My soul speaks fluent wanderlust.",
  "Made for runways, not routine.",
  "The map is calling. Always.",
  "Wanderlust is a mood, not a milestone.",
  "Trading bedrooms for boarding gates.",
  "Addicted to atlases.",
  "A heart with permanent jet lag.",
  "Visa stamps beat grocery receipts.",
  "Somewhere between here and there is home.",
  "My compass only points forward.",
  "Stamped, sealed, delivered to somewhere new.",
  "My love language is long-haul flights.",
  "Born with a passport in my hand.",
  "Travel runs through my veins.",
  "Currently browsing: one-way tickets.",
  "My Spotify is 90% airport lounge piano.",
  "Every sunrise in a new city is a love story.",
  "Forever falling in love with the unknown.",
  "The only souvenir I need is the way back.",
  "Nothing fits me like a window seat.",
  "Planning escapes is my cardio.",
  "Vacation mode: lifetime subscription.",
  "My search history is 99% flight deals.",
  "Daydreaming in destinations.",
  "I speak fluent wanderlust.",
  "Heart in Bali. Head at my desk.",
  "Passport pages: my favorite reading material.",
  "Always packing for somewhere.",
  "Home is where I drop my luggage.",
  "Every morning I wake up in love with tomorrow's flight.",
  "My boarding pass is my bookmark.",
  "An appetite for atlases.",
  "Gate closing. Heart opening.",
  "Feelings: wanderlust. Plans: imminent.",
  "I was born with the wrong hometown.",
  "Currently: everywhere.",
  "A soul stitched from airports.",
];

const ADVENTURE = [
  "Adventure is out there — and so am I.",
  "I don't need therapy. I need a one-way ticket.",
  "Leap first, look second.",
  "Life begins at the end of your comfort zone.",
  "Trading routines for routes.",
  "Let's go somewhere so small it's not on the map.",
  "If in doubt, go.",
  "Footloose and fancy-free across five continents.",
  "My feet itch for foreign soil.",
  "Some souls just weren't built for staying put.",
  "Born to explore.",
  "Pack light, live loud.",
  "Adventure never knocks. Go find it.",
  "Boots over bedrooms.",
  "Discomfort is the tuition.",
  "Go where the next yes lives.",
  "Risk it for the passport biscuit.",
  "Life is the adventure. Travel is the sampler.",
  "Fear less. Fly more.",
  "The best kind of tired.",
  "Map in one hand, sandwich in the other.",
  "Offline is the new luxury.",
  "I'd rather get lost than stay home.",
  "Adventure: the cure for what if.",
  "Out here, out loud, out there.",
  "First flight, last call.",
  "Hiked it. Loved it. Bought the hoodie.",
  "Mountains are my medicine.",
  "Trade worry for wonder.",
  "The brave have the best stories.",
  "My adrenaline is my atlas.",
  "Keep moving. Keep choosing.",
  "Forever chasing new skies.",
  "Scared. Go anyway.",
  "Pack snacks. Pack courage.",
  "Adventure has my phone number now.",
  "Go until something surprises you.",
  "Home base: wherever I'm brave enough to go.",
  "Say yes to the ridge.",
  "Fear is small compared to regret.",
  "One map. A hundred wrong turns. A great story.",
  "Run toward the thrill.",
  "Backpack, courage, go.",
  "Dirt road, full heart.",
  "Play outside forever.",
  "Stepped off the path. Found myself.",
  "The best views are off the trail.",
  "Adventure in my back pocket.",
  "Always choose the longer route.",
  "My comfort zone is a moving target.",
];

const MEMORIES = [
  "Every stamp is a story I get to keep.",
  "Collecting moments, not things.",
  "The best souvenirs are the memories.",
  "One map. A thousand stories.",
  "Counting countries. Counting my blessings.",
  "Each pin a memory. Each map a life.",
  "Made of sunsets and time zones.",
  "My heart beats in different time zones.",
  "These stamps aren't collected. They're earned.",
  "Travel is my love letter to myself.",
  "The map remembers what the calendar forgets.",
  "Miles spent. Memories gained.",
  "A life measured in stamps.",
  "Every page a chapter I can reread forever.",
  "The places I've been have shaped who I am.",
  "You can't buy this kind of atlas.",
  "My photos hold more years than my face.",
  "Memory-rich. Regret-free.",
  "My map is a time machine.",
  "These pins know me better than anyone.",
  "A scrapbook with passports for pages.",
  "Somewhere, a sunset is waiting for me again.",
  "The world is my photo album.",
  "What I remember, I carry.",
  "Every trip is a new version of me.",
  "My past is a patchwork of cities.",
  "Small moments. Bigger than the miles.",
  "I didn't just visit — I remember.",
  "Travel: cheaper than therapy, richer than gifts.",
  "Countries collected with a wide-open heart.",
  "Every sunrise somewhere new, tucked away.",
  "My memories wear hiking boots.",
  "Keepsakes and boarding passes.",
  "Love me, love my atlas.",
  "Postcards from a life well-traveled.",
  "A book of days spent elsewhere.",
  "The longer I live, the fuller the map.",
  "Moments that outlasted the flights.",
  "My favorite highlight reel is my map.",
  "Remember-the-view kind of life.",
  "Small stamps. Big meaning.",
  "A heart full of horizons.",
  "Memory lane is a flight path.",
  "The echo of every city still hums.",
  "Postcards from everywhere I ever loved.",
  "A trip fades. The memory doesn't.",
  "Feelings first, photos later.",
  "Stories I'll tell my grandkids.",
  "Every journey is an archive of my best self.",
  "Made rich by the places I've been.",
];

const HUMOR = [
  "Will travel for food.",
  "Currently disappearing into my next trip.",
  "Out of office. Out of continent.",
  "My carry-on has better organization than my life.",
  "Relationship status: committed to my passport.",
  "50% sunscreen, 50% adventure.",
  "Life is short. Book the flight.",
  "I'm not lost — I'm just exploring.",
  "Plot twist: I never came back.",
  "Still haven't unpacked from last time.",
  "Find me where the Wi-Fi is weakest.",
  "Passports over possessions.",
  "Frequent flyer. Infrequent cleaner.",
  "My bank account: disappointed. My passport: thrilled.",
  "Yes, I'm from somewhere. No, I'm never there.",
  "I've been everywhere. Except the gym.",
  "Currently on call with wanderlust.",
  "Boarding pass is my new spa day.",
  "I love naps and vacations — same vibe.",
  "Airports: the real self-care.",
  "Budgeting for flights is a personality trait.",
  "I deserve everything, especially this flight.",
  "Can't adult. Must travel.",
  "Will relocate for a better view.",
  "Travel log beats captain's log.",
  "Emotional support: boarding passes.",
  "Out of data. Full of life.",
  "Side effects may include chronic wanderlust.",
  "Got luggage, will travel (and complain).",
  "Collecting stamps is adult Pokémon.",
  "My therapist is the ocean.",
  "Oh, you don't have 17 suitcases? How cute.",
  "Weekend plans: upgrade, boarding pass, nap.",
  "Beach hair, don't care.",
  "My retirement plan is a backpack.",
  "Plan A: travel. Plan B: travel more.",
  "Every time I unpack, I'm already re-packing.",
  "Local beer tour = cultural research.",
  "I pack like I'm moving in.",
  "My laptop bag has more stamps than my birthday card.",
  "My airline status > my credit score.",
  "Tan lines over deadlines.",
  "Business class is a mood.",
  "Red wine plus window seat = love language.",
  "I'd rather have first-class flights than last-minute regrets.",
  "My love life is seasonal. My wanderlust isn't.",
  "Do I need it? No. Did I buy it in Istanbul? Yes.",
  "Life's too short for bad coffee and boring countries.",
  "If found, please return to the window seat.",
  "Carry-on full of chaos and lip balm.",
];

const GOALS = [
  "195 countries. One lifetime. Game on.",
  "On a first-name basis with every hotel lobby.",
  "Another stamp closer to the whole planet.",
  "Chasing the horizon, one country at a time.",
  "Working my way through the world's menu.",
  "Checking off the map, one stamp at a time.",
  "Following the sun around the world.",
  "Some collect cars. I collect coordinates.",
  "Every continent deserves at least one story.",
  "Inch by inch, country by country.",
  "The whole world is on my to-do list.",
  "Stamping my way across continents.",
  "My bucket list has its own filing cabinet.",
  "Life goal: out-travel my passport's pages.",
  "One passport at a time.",
  "Countries in progress: all of them.",
  "The world is too big to see once. I'm trying twice.",
  "Goal: more passport pages than years.",
  "One week. One country. Forever.",
  "A life lived in longitudes.",
  "Taking the scenic route. Always.",
  "Coming for your capital city.",
  "The atlas and I have an appointment.",
  "If it's on the map, it's on the list.",
  "I wake up and choose the world.",
  "Step by step, stamp by stamp.",
  "Seven seas. One me.",
  "Map > my manager.",
  "Living up to my unused vacation days.",
  "Breathing through the bucket list.",
  "One life. A lot of ink.",
  "Add another pin.",
  "Stamps to collect. Stories to tell.",
  "A lifetime of just one more.",
  "Counting countries like blessings.",
  "Map status: in progress forever.",
  "Goal: go everywhere at least once.",
  "The whole atlas, please.",
  "Counting flights like sheep.",
  "A small world if you work at it.",
  "Doubling my map every year.",
  "Paint every country, miss none.",
  "Travel goals: more stamps than last year.",
  "Step into every climate at least once.",
  "Crossing continents like checkboxes.",
  "I see every country as a promise.",
  "Filling my passport like a yearbook.",
  "Everywhere at some point.",
  "The more I stamp, the more I want.",
  "Life's to-do list: every country.",
];

const REFLECTIVE = [
  "You only truly understand home after leaving it.",
  "Distance is just a number until you walk it.",
  "The road teaches what the classroom cannot.",
  "Some places leave fingerprints on your soul.",
  "A passport full of stamps is a life well-spent.",
  "Every goodbye at an airport is a hello somewhere new.",
  "Borders divide countries, not people.",
  "We travel not to escape life, but so life doesn't escape us.",
  "The best views come after the hardest climbs.",
  "Maps are humble — they never brag about their places.",
  "Every trip rewrites who you are.",
  "Home is a feeling, not an address.",
  "Travel didn't change me. It revealed me.",
  "Our world is smaller than we think.",
  "Every path leads back to yourself.",
  "You never really leave anywhere. It stays.",
  "A traveler is never lost, only late.",
  "Leaving is the first act of coming home.",
  "The richest person is the one with the most stories.",
  "Every culture teaches you one thing about yourself.",
  "The world is best understood at ground level.",
  "Before travel, I thought I knew what cold was.",
  "Kindness translates everywhere.",
  "Strangers often make the best teachers.",
  "A meal shared with locals is the shortest flight.",
  "The sun rises on every culture just the same.",
  "You don't collect places. They collect you.",
  "You cannot hurry a sunset.",
  "All maps lead to the same starry sky.",
  "Slowness is a gift you give yourself.",
  "We all look the same from above.",
  "Miles are conversations with yourself.",
  "The best version of me lives abroad.",
  "You measure a life in seasons, not miles.",
  "A long flight is a short apology to yourself.",
  "Everywhere I've been changed the way I see home.",
  "Every city has the same moon.",
  "Luggage is temporary. Travel is permanent.",
  "We carry every place inside us.",
  "The world is older than our worries.",
  "The more I see, the less I know.",
  "Borders are our cleverest myth.",
  "Every stranger is a future friend in another language.",
  "Travel is the schoolteacher I never had.",
  "Real freedom is a full passport.",
  "Behind every postcard, a real life.",
  "Wealth is measured in stamps and stories.",
  "Memory keeps what the map can't hold.",
  "Travel empties the wallet, fills the soul.",
  "A journey begins long before the plane takes off.",
];

const POETIC = [
  "Salt in my hair, stamps in my book.",
  "Sand between my toes, sun on my face.",
  "The ocean has been my favorite teacher.",
  "Where mountains meet memories.",
  "Chasing waterfalls, not deadlines.",
  "Trails over traffic.",
  "The sky is my favorite ceiling.",
  "Coffee shops and cobblestones.",
  "Cities sleep. Wanderers dream.",
  "Lanterns, lattes, and long walks home.",
  "Every skyline tells a different story.",
  "Lost in alleys I'd never find again.",
  "Dawn breaks differently in every hemisphere.",
  "A thousand stars, none of them mine.",
  "Rivers write the oldest poems.",
  "The wind moves in no one's language.",
  "Some afternoons belong only to travelers.",
  "Twilight on a foreign street knows you.",
  "Mountains are patient lovers.",
  "Every harbor holds a different kind of hope.",
  "The road is a lover who never writes.",
  "Train tracks and typewriter keys.",
  "Autumn arrives differently in every country.",
  "Maps are love poems to the unknown.",
  "The world sings if you listen.",
  "Clouds I've known by name.",
  "Footsteps echo in my favorite churches.",
  "The horizon wears many colors.",
  "Ink stains and boarding passes.",
  "Sunsets are addresses that move.",
  "Some roads remember you back.",
  "Windows and wanderlust.",
  "A handful of rain in Prague. A gift.",
  "Dusk settles on the Danube like an old friend.",
  "Cafés on corners, diaries in pockets.",
  "A harbor. A coffee. A new beginning.",
  "The moon sounds different over the Sahara.",
  "Every sunrise is a country's hello.",
  "Bridges are gentler than borders.",
  "My favorite book is written in footprints.",
  "I trade clocks for tides.",
  "My winter lives elsewhere.",
  "Deltas hold the oldest music.",
  "Canyons whisper in vowels.",
  "All snow is the same until you taste it alone.",
  "Fog is the only friend of lonely travelers.",
  "Hemispheres swap my heart.",
  "I drink mornings like medicine.",
  "Horizons need no permission.",
  "Every map has a poet hidden in it.",
];

const SHORT_PUNCHY = [
  "Go. Just go.",
  "Make the map mine.",
  "Still chasing sunsets.",
  "Keep going. Keep glowing.",
  "Stamps > status.",
  "Tiny feet. Big atlas.",
  "Passport ready. Plans optional.",
  "Two feet. One world.",
  "Here for the horizons.",
  "Always almost packed.",
  "Two feet, one passport, zero regrets.",
  "A bucket list and a brave heart.",
  "Born to boarding-pass.",
  "Only forward.",
  "No map. Yes plan.",
  "Never not packing.",
  "Passport ≥ pillow.",
  "Moonbound. Map-led.",
  "More miles, more me.",
  "Go anyway.",
  "Always away.",
  "Always arriving.",
  "Here, but not really.",
  "Map-bitten.",
  "Exit row only.",
  "Window-seat soul.",
  "Adventure-fueled.",
  "Forever returning.",
  "Perfectly placeless.",
  "Wanderer. Repeat.",
  "Pin it.",
  "Everywhere, soon.",
  "Compass-hearted.",
  "Layover for life.",
  "Stamps in. Worry out.",
  "Tiny human. Huge map.",
  "Coffee. Map. Go.",
  "Boarding now.",
  "On the way.",
  "Packed. Present. Proud.",
  "Yes, and.",
  "Later, home.",
  "See you never.",
  "Hello, everywhere.",
  "Solo and soaring.",
  "Loaded with latitudes.",
  "Ink on. Shoes on.",
  "Onward.",
  "Always almost gone.",
  "Travel-fed.",
];

const DEEP = [
  "I travel because silence sounds different elsewhere.",
  "These lines on the map are my heartbeats.",
  "I'm made up of every place I've ever been.",
  "Wherever I go, I leave a little of me behind.",
  "I return from every trip slightly newer.",
  "Travel turns strangers into storytellers.",
  "A world unseen is a world unlived.",
  "My best self lives in a currency I haven't used yet.",
  "Roots hold me. Routes free me.",
  "Every departure is a small rebirth.",
  "I don't take vacations. I take adventures.",
  "Wanderer of maps, collector of moments.",
  "To travel is to translate the soul.",
  "My real language is longitude.",
  "A heart shaped by horizons.",
  "Every culture cracks you open a little.",
  "I've packed. I've unpacked. I've become.",
  "Travel is the quietest revolution.",
  "I owe myself everywhere I have never been.",
  "Every journey is an act of forgiveness.",
  "The places I fear most teach me most.",
  "Distance deepens desire.",
  "I collect countries like therapists.",
  "The road is the real teacher.",
  "Every border I cross, I cross myself.",
  "Who am I before, during, after this trip?",
  "Travel is a quiet confession.",
  "The only constant: I'm changed by leaving.",
  "I wrote my life in plane tickets.",
  "Each sunrise abroad remakes me.",
  "Journeys echo longest.",
  "Every arrival is a small ending.",
  "The farther I travel, the closer to myself.",
  "Sometimes home is where we least expect it.",
  "I've found myself in other people's languages.",
  "The lonely places taught me the most love.",
  "Motion is meditation for the restless.",
  "I travel to remember how small I am.",
  "The sun is the same, but I am different.",
  "No two returns are to the same person.",
  "I live twice — once here, once everywhere.",
  "Stars are the oldest postcards.",
  "Maps are love letters to our future selves.",
  "I am a little bit of every city I've walked in.",
  "The wind has taught me what no one else could.",
  "Every trip a small grief. Every return a small joy.",
  "We are the sum of our goodbyes.",
  "The deepest travel is inward.",
  "Some countries live inside me now.",
  "I was never lost. I was only becoming.",
];

const CLASSICS = [
  "Not all those who wander are lost.",
  "To travel is to live.",
  "The world is a book — and I'm on a new chapter.",
  "Travel far enough, you meet yourself.",
  "Oh, the places you'll go.",
  "Adventure is worthwhile in itself.",
  "The journey not the arrival matters.",
  "Once a year, go somewhere you've never been before.",
  "Life is either a daring adventure or nothing.",
  "Travel makes one modest.",
  "Go confidently in the direction of your dreams.",
  "The world is wider than you think.",
  "A ship in harbor is safe — but that's not what ships are for.",
  "Twenty years from now, regret the flights you didn't take.",
  "Blessed are the curious, for they have adventures.",
  "We shape our lives by every flight we take.",
  "Better to see something once than hear about it a thousand times.",
  "The real voyage of discovery begins with new eyes.",
  "Keep your face to the sun.",
  "The journey of a thousand miles begins with a single step.",
  "Stop worrying about the potholes and enjoy the journey.",
  "The world is big and I want to have a good look at it.",
  "You can shake the sand from your shoes — not your soul.",
  "Your destination is a new way of seeing.",
  "Wherever you go becomes a part of you.",
  "A mind stretched by a new experience can never go back.",
  "Jobs fill your pocket. Adventures fill your soul.",
  "Collect moments, not things.",
  "Travel brings power and love back into your life.",
  "The world is a book.",
  "Take nothing but pictures.",
  "There are no foreign lands. Only the traveler is foreign.",
  "When in doubt, travel.",
  "One day I'll remember this. That's why I'm going.",
  "The way we experience the world is how we remember it.",
  "Certain things in life simply have to be experienced.",
  "I haven't been everywhere, but it's on my list.",
  "Let your memories be your travel agent.",
  "Fill your life with experiences, not things.",
  "Live your life by a compass, not a clock.",
];

const SEASONAL = [
  "Four seasons, many countries.",
  "Midnight sun, polar night — I want them both.",
  "Chasing summer year-round.",
  "Snow in one hemisphere, sand in the other.",
  "Autumn in Kyoto ruined all other autumns.",
  "Spring in Paris. The rest of the year, elsewhere.",
  "Summer on every continent. At least once.",
  "Winter's warmest lies in Tel Aviv.",
  "Monsoon has taught me patience.",
  "April for orchards. October for oceans.",
  "Aurora, cherry blossoms, or bust.",
  "The seasons turn, and so do I.",
  "Always running from a winter somewhere.",
  "Falling in love with fall, everywhere.",
  "My summer is shaped like a backpack.",
  "December in the Southern Hemisphere is my Christmas.",
  "Walked through four seasons in one country.",
  "Made for moonlit shoulder seasons.",
  "I season-chase like others chase deadlines.",
  "The shortest winter is in someone else's spring.",
];

// Combined pool — ~500 taglines
export const TAGLINES = [
  ...WANDERLUST, ...ADVENTURE, ...MEMORIES, ...HUMOR,
  ...GOALS, ...REFLECTIVE, ...POETIC, ...SHORT_PUNCHY,
  ...DEEP, ...CLASSICS, ...SEASONAL,
];

// Fisher-Yates partial shuffle. `excludePool` lets the caller avoid
// immediately repeating the currently visible batch.
export function pickRandomTaglines(count = 8, excludePool = []) {
  const exclude = new Set(excludePool);
  const remaining = TAGLINES.filter(t => !exclude.has(t));
  const arr = remaining.slice();
  const n = Math.min(count, arr.length);
  for (let i = 0; i < n; i++) {
    const j = i + Math.floor(Math.random() * (arr.length - i));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, n);
}

// Single random tagline for the "Generate by AI" button. `exclude` avoids
// handing back the same line the user just got.
export function pickRandomTagline(exclude = '') {
  const pool = exclude ? TAGLINES.filter(t => t !== exclude) : TAGLINES;
  return pool[Math.floor(Math.random() * pool.length)];
}
