// Central manifest of every published blog post. The blog index, sitemap,
// and per-post pages all read from this list — keep it in sync when adding posts.
export const POSTS = [
  {
    slug: 'europe-travel-guide-2026',
    title: "The Ultimate Europe Travel Guide 2026: 44 Countries, One Continent, Endless Possibilities",
    description:
      "Everything you need to plan a Europe trip in 2026 — best countries by travel style, Schengen rules, ETIAS launch, train vs plane math, budget by region, safest destinations, and the 15 mistakes first-timers make.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 16,
    category: 'Europe Travel',
    tags: ['Europe', 'Travel Guide', 'Schengen', 'Bucket List'],
    heroEmoji: '🇪🇺',
  },
  {
    slug: 'two-week-europe-itinerary-2026',
    title: "The Perfect 2-Week Europe Itinerary: London → Paris → Amsterdam → Berlin → Prague → Rome (2026)",
    description:
      "A tested 14-day first-timer Europe itinerary covering London, Paris, Amsterdam, Berlin, Prague and Rome — with exact train/flight logistics, daily schedule, lodging picks, and cost breakdown.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Europe Travel',
    tags: ['Europe', 'Itinerary', 'First Time Europe', 'Trip Planning'],
    heroEmoji: '🗺️',
  },
  {
    slug: 'best-european-cities-2026',
    title: "The 15 Best European Cities to Visit in 2026 (Ranked by Travelers)",
    description:
      "The 15 European cities worth your vacation time in 2026 — ranked across six dimensions by our 4,180-traveler panel. Deep-dives on Rome, Paris, Barcelona, Lisbon, Amsterdam, Prague, Porto, Vienna and the underrated sleepers.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Europe Travel',
    tags: ['Europe', 'Cities', 'Ranked', 'Bucket List'],
    heroEmoji: '🏙️',
  },
  {
    slug: 'interrail-eurail-guide-2026',
    title: "Interrail & Eurail Guide 2026: How to Actually Plan a Train Trip Across Europe",
    description:
      "The complete 2026 Interrail / Eurail Pass guide — which pass to buy, break-even math, the 10 best train routes in Europe, reservation rules, and the mistakes that turn a dream into chaos.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Europe Travel',
    tags: ['Europe', 'Trains', 'Interrail', 'Eurail', 'Backpacking'],
    heroEmoji: '🚆',
  },
  {
    slug: 'europe-budget-travel-2026',
    title: "Europe on a Budget: Cost of Travel in 30 European Countries (2026)",
    description:
      "A data-backed cost comparison of all 30 major European countries in 2026 — which are the cheapest, which have quietly gotten pricey, realistic daily budgets, and the 12 saving tactics that genuinely cut your spend by a third.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Europe Travel',
    tags: ['Europe', 'Budget Travel', 'Cost Comparison'],
    heroEmoji: '💶',
  },
  {
    slug: 'best-european-beaches-2026',
    title: "The 20 Best Beaches in Europe (2026): Greece, Italy, Croatia, Spain & Beyond",
    description:
      "The 20 most beautiful European beaches for summer 2026 — from Greek islands and Amalfi Coast to Croatian coves, Portuguese Algarve and Spanish secrets. Where to go, when, and which ones deserve the hype.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 12,
    category: 'Europe Travel',
    tags: ['Europe', 'Beaches', 'Summer', 'Greece', 'Croatia'],
    heroEmoji: '🏖️',
  },
  {
    slug: 'italy-travel-guide-2026',
    title: "The Ultimate Italy Travel Guide (2026): 20 Regions, Endless Beauty",
    description:
      "Everything you need to plan an Italy trip in 2026 — best time to visit, 20 regions, food by region, trains, budget, visa and the 12 mistakes first-timers always make. Rome, Florence, Venice, Amalfi, Tuscany and more.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 15,
    category: 'Italy Travel',
    tags: ['Italy', 'Travel Guide', 'Europe', 'Bucket List'],
    heroEmoji: '🇮🇹',
  },
  {
    slug: 'two-week-italy-itinerary-2026',
    title: "The Perfect 2-Week Italy Itinerary: Rome → Florence → Venice → Amalfi (2026)",
    description:
      "A tested 14-day Italy itinerary covering Rome, Florence + Tuscany, Venice, Cinque Terre and the Amalfi Coast — with train logistics, lodging picks, cost breakdown and the stops most first-timers skip.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Italy Travel',
    tags: ['Italy', 'Itinerary', 'Rome', 'Florence', 'Venice'],
    heroEmoji: '🗺️',
  },
  {
    slug: 'best-italy-regions-2026',
    title: "Italy's 10 Best Regions for Travelers in 2026: Tuscany, Amalfi, Sicily & More (Ranked)",
    description:
      "The 10 Italian regions worth your vacation time in 2026 — ranked by a 6-dimension traveler score. Deep-dives on Tuscany, Campania, Veneto, Sicily, Piedmont, Puglia and the underrated regions most skip.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Italy Travel',
    tags: ['Italy', 'Regions', 'Tuscany', 'Amalfi', 'Ranked'],
    heroEmoji: '🌄',
  },
  {
    slug: 'italian-food-guide-2026',
    title: "Italian Food Guide: 30 Dishes You Must Try in Italy — by Region (2026)",
    description:
      "Italian food is 20 distinct regional cuisines, not one. The 30 dishes every traveler must try — carbonara in Rome, bistecca in Florence, cacio e pepe, pizza in Naples, risotto in Milan, arancini in Sicily — and where to eat each.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Italy Travel',
    tags: ['Italy', 'Food', 'Italian Cuisine', 'Pasta', 'Pizza'],
    heroEmoji: '🍝',
  },
  {
    slug: 'amalfi-coast-guide-2026',
    title: "Amalfi Coast Complete Guide 2026: Positano, Amalfi, Ravello & Capri",
    description:
      "The definitive 2026 Amalfi Coast guide — where to stay (Positano vs Amalfi vs Ravello), how to actually get around (ferry beats road), best restaurants, Capri day-trip, driving the SS163 and the secret alternatives to the famous three towns.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Italy Travel',
    tags: ['Italy', 'Amalfi Coast', 'Positano', 'Capri'],
    heroEmoji: '🏖️',
  },
  {
    slug: 'italy-budget-travel-2026',
    title: "Italy on a Budget: How to Travel Italy for €50, €100 or €200 a Day (2026)",
    description:
      "Three fully-costed 2026 Italy budgets — €50/day backpacker, €100/day comfortable mid-range, €200/day comfort tier. Real 2026 prices, train math, agriturismo picks, and the money-saving tactics Italians actually use.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 12,
    category: 'Italy Travel',
    tags: ['Italy', 'Budget Travel', 'Europe', 'Costs'],
    heroEmoji: '💶',
  },
  {
    slug: 'thailand-travel-guide-2026',
    title: "The Ultimate Thailand Travel Guide (2026): Everything You Need to Know",
    description:
      "A complete 2026 Thailand guide — best time to visit, regions, visa rules, budget tiers, food, transport, beaches and the 12 mistakes first-timers make. Bangkok, Chiang Mai, Phuket and beyond.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 15,
    category: 'Thailand Travel',
    tags: ['Thailand', 'Travel Guide', 'Southeast Asia', 'Bucket List'],
    heroEmoji: '🇹🇭',
  },
  {
    slug: 'two-week-thailand-itinerary-2026',
    title: "The Perfect 2-Week Thailand Itinerary: Bangkok → Chiang Mai → Phuket → Krabi (2026)",
    description:
      "A tested 14-day Thailand itinerary covering Bangkok temples, Chiang Mai mountains, Phuket beaches and Krabi island-hopping — with daily logistics, lodging picks and cost breakdown.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Thailand Travel',
    tags: ['Thailand', 'Itinerary', 'Bangkok', 'Phuket'],
    heroEmoji: '🛕',
  },
  {
    slug: 'best-thailand-islands-2026',
    title: "The 10 Best Thai Islands in 2026: Phi Phi, Koh Samui, Koh Tao & More (Ranked)",
    description:
      "The 10 Thai islands worth your vacation time in 2026 — ranked by a 6-dimension score. Deep-dives on Phi Phi, Koh Samui, Koh Tao, Koh Lanta, Koh Phangan, Koh Lipe, Railay and the underrated sleepers.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Thailand Travel',
    tags: ['Thailand', 'Islands', 'Phuket', 'Koh Samui'],
    heroEmoji: '🏝️',
  },
  {
    slug: 'thai-food-guide-2026',
    title: "Thai Food Guide: 25 Dishes You Must Try in Thailand (2026)",
    description:
      "A pragmatic 2026 guide to Thai cuisine — the 25 dishes that matter, from pad thai and green curry to som tum, tom yum, khao soi, mango sticky rice and the street food that's Thailand's real soul.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Thailand Travel',
    tags: ['Thailand', 'Food', 'Thai Cuisine', 'Street Food'],
    heroEmoji: '🍜',
  },
  {
    slug: 'bangkok-complete-guide-2026',
    title: "Bangkok Complete Guide 2026: 5 Days in the World's Wildest Capital",
    description:
      "The definitive 2026 Bangkok guide — where to stay, what to eat, the 12 temples worth your time, night markets, rooftop bars, airport logistics and how to actually enjoy a 5-day Bangkok trip.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Thailand Travel',
    tags: ['Thailand', 'Bangkok', 'City Guide'],
    heroEmoji: '🏙️',
  },
  {
    slug: 'thailand-budget-travel-2026',
    title: "Thailand on a Budget: How to Travel for $25, $60 or $120 a Day (2026)",
    description:
      "Three fully-costed 2026 Thailand budgets — $25/day backpacker, $60/day mid-range, $120/day comfort tier. Real 2026 prices, hostel picks, night-bus math, and the saving tactics locals use.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 12,
    category: 'Thailand Travel',
    tags: ['Thailand', 'Budget Travel', 'Backpacking'],
    heroEmoji: '💸',
  },
  {
    slug: 'japan-travel-guide-2026',
    title: "The Ultimate Japan Travel Guide (2026): 47 Prefectures, One Unforgettable Country",
    description:
      "Everything you need to plan a Japan trip in 2026 — best time to visit, JR Pass math, region-by-region highlights, food, etiquette, budget tiers, cherry blossom timing and the 12 mistakes first-time visitors make.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 15,
    category: 'Japan Travel',
    tags: ['Japan', 'Travel Guide', 'Asia', 'Bucket List'],
    heroEmoji: '🇯🇵',
  },
  {
    slug: 'two-week-japan-itinerary-2026',
    title: "The Perfect 2-Week Japan Itinerary: Tokyo → Kyoto → Osaka → Hiroshima (2026)",
    description:
      "A tested 14-day Japan itinerary covering Tokyo, Kyoto, Osaka, Hiroshima, Hakone and Kanazawa — with exact JR Pass logistics, daily schedule, ryokan vs hotel picks, cost breakdown and the stops most itineraries skip.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Japan Travel',
    tags: ['Japan', 'Itinerary', 'Tokyo', 'Kyoto', 'Trip Planning'],
    heroEmoji: '🗾',
  },
  {
    slug: 'best-japan-regions-2026',
    title: "Japan's 9 Best Regions for Travelers in 2026: Tokyo, Kyoto, Hokkaido & More (Ranked)",
    description:
      "The 9 Japanese regions worth your vacation days in 2026 — ranked by a 6-dimension traveler score. Deep-dives on Kanto, Kansai, Hokkaido, Okinawa, Tohoku, and the underrated regions most itineraries skip.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Japan Travel',
    tags: ['Japan', 'Regions', 'Ranked', 'Bucket List'],
    heroEmoji: '🗻',
  },
  {
    slug: 'japanese-food-guide-2026',
    title: "Japanese Food Guide: 30 Dishes You Must Try in Japan (2026)",
    description:
      "A pragmatic 2026 guide to the 30 Japanese dishes that genuinely matter — sushi, ramen, tempura, okonomiyaki, unagi, yakiniku, kaiseki — organized by region, with our best-in-class restaurant picks for each.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Japan Travel',
    tags: ['Japan', 'Food', 'Japanese Cuisine', 'Sushi', 'Ramen'],
    heroEmoji: '🍣',
  },
  {
    slug: 'japan-cherry-blossom-2026',
    title: "Japan Cherry Blossom 2026: Complete Sakura Forecast, Hanami Spots & Peak Dates by Region",
    description:
      "The 2026 sakura forecast — when cherry blossoms will peak in Tokyo, Kyoto, Osaka, Hokkaido and every major region. Best hanami viewing spots, how to book a cherry-blossom trip, and which year to go if 2026 is already booked.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 12,
    category: 'Japan Travel',
    tags: ['Japan', 'Cherry Blossom', 'Sakura', 'Hanami', '2026'],
    heroEmoji: '🌸',
  },
  {
    slug: 'japan-budget-travel-2026',
    title: "Japan on a Budget: How to Travel Japan for $60, $120 or $250 a Day (2026)",
    description:
      "Three fully-costed 2026 Japan budgets — the $60/day backpacker, the $120/day comfortable mid-range, and the $250/day comfort tier. Real 2026 prices, JR Pass math, hostel/ryokan picks, and money-saving tactics locals actually use.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Japan Travel',
    tags: ['Japan', 'Budget Travel', 'JR Pass', 'Costs'],
    heroEmoji: '💴',
  },
  {
    slug: 'philippines-travel-guide-2026',
    title: "The Ultimate Philippines Travel Guide (2026): 7,641 Islands, 17 Regions, One Incredible Country",
    description:
      "Everything you need to plan a Philippines trip in 2026 — best time to visit, 3 main island groups, visa rules, realistic budgets, region-by-region highlights, food, safety and the 10 mistakes first-timers always make.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 15,
    category: 'Philippines Travel',
    tags: ['Philippines', 'Travel Guide', 'Southeast Asia', 'Bucket List'],
    heroEmoji: '🇵🇭',
  },
  {
    slug: 'two-week-philippines-itinerary-2026',
    title: "The Perfect 2-Week Philippines Itinerary: Manila → Palawan → Cebu → Siargao (2026)",
    description:
      "A pragmatic, tested 14-day Philippines itinerary covering Manila, El Nido, Coron, Cebu, Bohol, and Siargao — with exact flight/ferry logistics, daily budgets, where to sleep, and the stops most itineraries skip.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Philippines Travel',
    tags: ['Philippines', 'Itinerary', '2 Weeks', 'Trip Planning'],
    heroEmoji: '🗺️',
  },
  {
    slug: 'best-philippine-islands-2026',
    title: "7 Best Philippine Islands to Visit in 2026: Palawan, Siargao, Cebu & More (Ranked)",
    description:
      "The seven Philippine islands worth your vacation days in 2026 — ranked by our data-backed traveler score. Deep-dives on Palawan, Boracay, Cebu, Bohol, Siargao, Batanes and Siquijor, plus which to pair for a 2-island trip.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 14,
    category: 'Philippines Travel',
    tags: ['Philippines', 'Islands', 'Palawan', 'Siargao', 'Ranked'],
    heroEmoji: '🏝️',
  },
  {
    slug: 'philippines-beaches-2026',
    title: "The 15 Most Beautiful Beaches in the Philippines (2026 Complete Guide)",
    description:
      "From Boracay's White Beach to hidden pristine coves in Palawan and Siargao — the 15 Philippine beaches that genuinely deserve bucket-list status in 2026. Location, best time, how to get there, and honest crowd-levels for each.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 12,
    category: 'Philippines Travel',
    tags: ['Philippines', 'Beaches', 'White Sand', 'Island Hopping'],
    heroEmoji: '🏖️',
  },
  {
    slug: 'filipino-food-guide-2026',
    title: "Filipino Food Guide: 25 Dishes You Must Try in the Philippines (2026)",
    description:
      "A pragmatic, deliciously opinionated guide to Filipino cuisine in 2026 — the 25 dishes that matter, from adobo and sinigang to halo-halo, lechon, pancit, ube, and the street-food you shouldn't leave without trying. Where to eat each one.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 13,
    category: 'Philippines Travel',
    tags: ['Philippines', 'Food', 'Filipino Cuisine', 'Foodie'],
    heroEmoji: '🍲',
  },
  {
    slug: 'philippines-budget-travel-2026',
    title: "Philippines on a Budget: How to Travel for $25, $50 or $100 a Day (2026)",
    description:
      "Three fully-costed 2026 Philippines budgets for every kind of traveler — the $25/day backpacker, the $50/day comfortable mid-range, and the $100/day comfort tier. Real 2026 prices, actual hostels, ferry schedules and money-saving tactics.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-22',
    readMinutes: 12,
    category: 'Philippines Travel',
    tags: ['Philippines', 'Budget Travel', 'Backpacking', 'Costs'],
    heroEmoji: '💸',
  },
  {
    slug: 'usa-bucket-list-100-places',
    title: "USA Bucket List: 100 Must-See Places by State (Interactive Map & Checklist)",
    description:
      "The definitive 100-place US bucket list, organized by state and category — national parks, historic sites, food capitals, quirky roadside icons and off-the-beaten-path wonders. Interactive map, printable checklist and regional trip-planning tips.",
    ogImage: '/diego-jimenez-A-NVHPka9Rk-unsplash.jpg',
    datePublished: '2026-04-21',
    readMinutes: 16,
    category: 'USA Travel',
    tags: ['Bucket List', 'USA', 'Travel Planning', 'Interactive Map'],
    heroEmoji: '🇺🇸',
  },
  {
    slug: 'american-travel-trends-2026',
    title: "How Americans Actually Travel in 2026: The Definitive Data & Trend Report",
    description:
      "A data-rich 2026 report on how Americans really travel — average trip length, spend, top destinations, work-from-anywhere growth, domestic vs international share, generational patterns and the five trends reshaping US tourism this year.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-21',
    readMinutes: 13,
    category: 'USA Travel',
    tags: ['Travel Data', 'US Trends', 'Tourism Report', '2026'],
    heroEmoji: '📊',
  },
  {
    slug: 'pacific-coast-highway-ultimate-guide-2026',
    title: "Pacific Coast Highway: The Ultimate 655-Mile California Road Trip (2026 Guide)",
    description:
      "Drive California's Highway 1 end to end in 2026 — Big Sur to the Redwoods, Santa Monica to Mendocino. Full 7-day itinerary, mileage breakdown, viewpoint-by-viewpoint stops, realistic budget tables and best-season weather data.",
    ogImage: '/spencer-davis-0QcSnCM0aMc-unsplash.jpg',
    datePublished: '2026-04-21',
    readMinutes: 13,
    category: 'USA Travel',
    tags: ['PCH', 'California', 'Road Trip', 'Big Sur', 'Itinerary'],
    heroEmoji: '🌊',
  },
  {
    slug: 'most-visited-national-parks-2026',
    title: "The 10 Most-Visited US National Parks (2026): Data, Maps & Crowd-Avoidance Guide",
    description:
      "Annual visitation data, state-by-state map, busiest months chart and practical crowd-avoidance strategies for America's ten most-visited national parks — plus five underrated alternatives that deliver the same wow without the shuttle-bus line.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-21',
    readMinutes: 12,
    category: 'USA Travel',
    tags: ['National Parks', 'USA', 'Travel Data', 'Bucket List'],
    heroEmoji: '🏞️',
  },
  {
    slug: 'us-states-ranked-for-travelers-2026',
    title: "All 50 US States Ranked for Travelers in 2026: A Data-Driven Bucket-List Guide",
    description:
      "The StampYourMap team scored all 50 US states across six dimensions — cost, nature, culture, food, bucket-list iconicity and ease-of-travel — to produce the definitive 2026 ranking. Full table, interactive map, best-by-category picks, and the underrated sleepers everyone overlooks.",
    ogImage: '/tom-barrett-M0AWNxnLaMw-unsplash.jpg',
    datePublished: '2026-04-21',
    readMinutes: 14,
    category: 'USA Travel',
    tags: ['US States', 'Bucket List', 'Travel Rankings', 'USA', 'Trip Planning'],
    heroEmoji: '🗽',
  },
  {
    slug: 'route-66-ultimate-guide-2026',
    title: "Route 66 Revival: The Ultimate 2,448-Mile American Road Trip Guide (2026)",
    description:
      "A data-rich 2026 guide to driving Route 66 end to end — 8 states, 2,448 miles, week-by-week itinerary, best-time-to-drive weather data, realistic budget tables, and the can't-miss roadside stops that make the Mother Road unforgettable.",
    ogImage: '/felix-rostig-UmV2wr-Vbq8-unsplash.jpg',
    datePublished: '2026-04-21',
    readMinutes: 12,
    category: 'USA Travel',
    tags: ['Route 66', 'Road Trip', 'USA', 'Bucket List', 'Itinerary'],
    heroEmoji: '🛣️',
  },
];

export function getPostBySlug(slug) {
  return POSTS.find(p => p.slug === slug) || null;
}
